{
 "title": "GLPI Dashboard (Tickets)",
 "description": "GLPI Dashboard\r\nShow somes informations on tickets",
 "tags": [
  "glpi-app",
  "imported"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_GLPI", "label": "GLPI Datasource", "query": "ddurieux-glpi-datasource" },
   { "name": "URL_GLPI", "query": "$URL_GLPI" }
  ]
 },
 "panels": [
  {
   "title": "Incident / Request Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Incident",
     "channel": { "name": "" },
     "col_0": { "group": "Default", "label": "------", "number": "0" },
     "col_1": { "group": "Default", "label": "------", "number": "0" },
     "col_10": { "group": "Default", "label": "------", "number": "0" },
     "col_11": { "group": "Default", "label": "------", "number": "0" },
     "col_2": { "group": "Default", "label": "------", "number": "0" },
     "col_3": { "group": "Default", "label": "------", "number": "0" },
     "col_4": { "group": "Default", "label": "------", "number": "0" },
     "col_5": { "group": "Default", "label": "------", "number": "0" },
     "col_6": { "group": "Default", "label": "------", "number": "0" },
     "col_7": { "group": "Default", "label": "------", "number": "0" },
     "col_8": { "group": "Default", "label": "------", "number": "0" },
     "col_9": { "group": "Default", "label": "------", "number": "0" },
     "datefield": {
      "group": "Special / be careful",
      "label": "Do not use date search (get all data)",
      "number": "-1"
     },
     "device": { "name": "" },
     "dynamicsplit": { "group": "Default", "label": "------", "number": "0" },
     "group": { "name": "" },
     "options": {
      "includeDeviceName": false,
      "includeSensorName": false,
      "mode": {
       "filterProperty": {},
       "name": "Metrics",
       "textProperty": {},
       "textValueFrom": {},
       "value": 1
      }
     },
     "query": "${URL_GLPI}front/ticket.php?is_deleted=0&as_map=0&criteria[0][field]=14&criteria[0][searchtype]=equals&criteria[0][value]=1&search=Rechercher&itemtype=Ticket&start=0",
     "raw": { "queryString": "", "uri": "" },
     "sensor": { "name": "" }
    },
    {
     "alias": "Request",
     "col_0": { "group": "Default", "label": "------", "number": "0" },
     "col_1": { "group": "Default", "label": "------", "number": "0" },
     "col_10": { "group": "Default", "label": "------", "number": "0" },
     "col_11": { "group": "Default", "label": "------", "number": "0" },
     "col_2": { "group": "Default", "label": "------", "number": "0" },
     "col_3": { "group": "Default", "label": "------", "number": "0" },
     "col_4": { "group": "Default", "label": "------", "number": "0" },
     "col_5": { "group": "Default", "label": "------", "number": "0" },
     "col_6": { "group": "Default", "label": "------", "number": "0" },
     "col_7": { "group": "Default", "label": "------", "number": "0" },
     "col_8": { "group": "Default", "label": "------", "number": "0" },
     "col_9": { "group": "Default", "label": "------", "number": "0" },
     "datefield": {
      "group": "Special / be careful",
      "label": "Do not use date search (get all data)",
      "number": "-1"
     },
     "dynamicsplit": { "group": "Default", "label": "------", "number": "0" },
     "query": "${URL_GLPI}front/ticket.php?is_deleted=0&as_map=0&criteria[0][field]=14&criteria[0][searchtype]=equals&criteria[0][value]=2&search=Rechercher&itemtype=Ticket&start=0"
    }
   ]
  },
  {
   "title": "New ticket",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "col_0": { "group": "Default", "label": "------", "number": "0" },
     "col_1": { "group": "Default", "label": "------", "number": "0" },
     "col_10": { "group": "Default", "label": "------", "number": "0" },
     "col_11": { "group": "Default", "label": "------", "number": "0" },
     "col_2": { "group": "Default", "label": "------", "number": "0" },
     "col_3": { "group": "Default", "label": "------", "number": "0" },
     "col_4": { "group": "Default", "label": "------", "number": "0" },
     "col_5": { "group": "Default", "label": "------", "number": "0" },
     "col_6": { "group": "Default", "label": "------", "number": "0" },
     "col_7": { "group": "Default", "label": "------", "number": "0" },
     "col_8": { "group": "Default", "label": "------", "number": "0" },
     "col_9": { "group": "Default", "label": "------", "number": "0" },
     "datefield": {
      "group": "Special / be careful",
      "label": "Do not use date search (get all data)",
      "number": "-1"
     },
     "dynamicsplit": { "group": "Default", "label": "------", "number": "0" },
     "query": "${URL_GLPI}front/ticket.php?is_deleted=0&as_map=0&criteria[0][field]=12&criteria[0][searchtype]=equals&criteria[0][value]=1&search=Search&itemtype=Ticket&start=0"
    }
   ]
  },
  {
   "title": "Waiting for approval (not closed)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "col_0": { "group": "", "label": "------", "number": "0" },
     "col_1": { "group": "", "label": "------", "number": "0" },
     "col_10": { "group": "Default", "label": "------", "number": "0" },
     "col_11": { "group": "Default", "label": "------", "number": "0" },
     "col_2": { "group": "", "label": "------", "number": "0" },
     "col_3": { "group": "", "label": "------", "number": "0" },
     "col_4": { "group": "", "label": "------", "number": "0" },
     "col_5": { "group": "", "label": "------", "number": "0" },
     "col_6": { "group": "Default", "label": "------", "number": "0" },
     "col_7": { "group": "Default", "label": "------", "number": "0" },
     "col_8": { "group": "Default", "label": "------", "number": "0" },
     "col_9": { "group": "Default", "label": "------", "number": "0" },
     "datefield": {
      "group": "Special / be careful",
      "label": "Do not use date search (get all data)",
      "number": "-1"
     },
     "dynamicsplit": { "group": "Default", "label": "------", "number": "0" },
     "query": "${URL_GLPI}front/ticket.php?is_deleted=0&as_map=0&criteria[0][field]=52&criteria[0][searchtype]=equals&criteria[0][value]=2&criteria[1][link]=AND+NOT&criteria[1][field]=12&criteria[1][searchtype]=equals&criteria[1][value]=6&search=Search&itemtype=Ticket&start=0"
    }
   ]
  },
  {
   "title": "Ticket not solved",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "col_0": { "group": "", "label": "------", "number": "0" },
     "col_1": { "group": "", "label": "------", "number": "0" },
     "col_10": { "group": "Default", "label": "------", "number": "0" },
     "col_11": { "group": "Default", "label": "------", "number": "0" },
     "col_2": { "group": "", "label": "------", "number": "0" },
     "col_3": { "group": "", "label": "------", "number": "0" },
     "col_4": { "group": "", "label": "------", "number": "0" },
     "col_5": { "group": "", "label": "------", "number": "0" },
     "col_6": { "group": "Default", "label": "------", "number": "0" },
     "col_7": { "group": "Default", "label": "------", "number": "0" },
     "col_8": { "group": "Default", "label": "------", "number": "0" },
     "col_9": { "group": "Default", "label": "------", "number": "0" },
     "datefield": {
      "group": "Special / be careful",
      "label": "Do not use date search (get all data)",
      "number": "-1"
     },
     "dynamicsplit": { "group": "Default", "label": "------", "number": "0" },
     "query": "${URL_GLPI}front/ticket.php?is_deleted=0&as_map=0&criteria[0][field]=12&criteria[0][searchtype]=equals&criteria[0][value]=notold&search=Search&itemtype=Ticket&start=0"
    }
   ]
  },
  {
   "title": "Number of tickets created (24 last hours)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "col_0": { "group": "Default", "label": "------", "number": "0" },
     "col_1": { "group": "Default", "label": "------", "number": "0" },
     "col_10": { "group": "Default", "label": "------", "number": "0" },
     "col_11": { "group": "Default", "label": "------", "number": "0" },
     "col_2": { "group": "Default", "label": "------", "number": "0" },
     "col_3": { "group": "Default", "label": "------", "number": "0" },
     "col_4": { "group": "Default", "label": "------", "number": "0" },
     "col_5": { "group": "Default", "label": "------", "number": "0" },
     "col_6": { "group": "Default", "label": "------", "number": "0" },
     "col_7": { "group": "Default", "label": "------", "number": "0" },
     "col_8": { "group": "Default", "label": "------", "number": "0" },
     "col_9": { "group": "Default", "label": "------", "number": "0" },
     "datefield": { "group": "Caractéristiques", "label": "Date d'ouverture", "number": "15" },
     "dynamicsplit": { "group": "Default", "label": "------", "number": "0" },
     "query": "${URL_GLPI}front/ticket.php?is_deleted=0&as_map=0&criteria[0][field]=12&criteria[0][searchtype]=equals&criteria[0][value]=all&search=Rechercher&itemtype=Ticket&start=0"
    }
   ]
  },
  {
   "title": "Last tickets",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "col_0": { "group": "Caractéristiques", "label": "Titre", "number": "1" },
     "col_1": { "group": "Demandeur", "label": "Demandeur", "number": "4" },
     "col_10": { "group": "Default", "label": "------", "number": "0" },
     "col_11": { "group": "Default", "label": "------", "number": "0" },
     "col_2": { "group": "Caractéristiques", "label": "Priorité", "number": "3" },
     "col_3": { "group": "Caractéristiques", "label": "Entité", "number": "80" },
     "col_4": { "group": "Caractéristiques", "label": "Date d'ouverture", "number": "15" },
     "col_5": { "group": "Caractéristiques", "label": "Catégorie", "number": "7" },
     "col_6": { "group": "Default", "label": "------", "number": "0" },
     "col_7": { "group": "Default", "label": "------", "number": "0" },
     "col_8": { "group": "Default", "label": "------", "number": "0" },
     "col_9": { "group": "Default", "label": "------", "number": "0" },
     "cols": { "0": "1", "1": "4", "2": "3" },
     "colsa": { "group": "Caractéristiques", "label": "Titre", "number": "1" },
     "counter": "yes",
     "datefield": {
      "group": "Special / be careful",
      "label": "Do not use date search (get all data)",
      "number": "-1"
     },
     "dynamicsplit": { "group": "Default", "label": "------", "number": "0" },
     "query": "${URL_GLPI}front/ticket.php?is_deleted=0&as_map=0&criteria[0][field]=12&criteria[0][searchtype]=equals&criteria[0][value]=notold&search=Search&itemtype=Ticket&start=0"
    }
   ]
  }
 ]
}