#-----------------------------------------------------------------------------------------------------------
# filename: startVM.yml
#-----------------------------------------------------------------------------------------------------------
# Introduction
# Script to be used in advanced monitoring
#-----------------------------------------------------------------------------------------------------------
# Copyright
#
# Copyright (C) 1989, 1991 Free Software Foundation, Inc., [http://fsf.org/]
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
# Everyone is permitted to copy and distribute verbatim copies
# of this license document, but changing it is not allowed.
#
#-----------------------------------------------------------------------------------------------------------
# Version:      1.0.0
# Author:       Luis Henrique Vinhali <vinhali@outlook.com>
#
# Changelog:
# 1.0.0 02-02-2020      Inital version
#
#-----------------------------------------------------------------------------------------------------------
---
- name: Starting VM Virtual Box
  hosts:
    - all
  tasks:
    - include_role:
        name: startVM
        tasks_from: startWebServer
