{
 "title": "Zabbix Server Dashboard",
 "description": "Linux - Zabbix Server  - Zabbix MySQL",
 "tags": [ "zabbix34" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "group", "label": "GROUP", "query": "*" },
   { "name": "host", "label": "HOST", "query": "$group.*" }
  ]
 },
 "panels": [
  { "title": "System Overview of $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "content": "<br>\n<h1 style=\"text-align: center;\"><img src=\"https://images.esp-online.com/thumbnails/aws_solution_list_thumbnail/2614/9455/9402/ZABBIX_LOGO.jpg\" alt=\"\" width=\"191\" height=\"50\" /></h1>\n<h1 style=\"text-align: center;\"><span style=\"color: #ffffff;\"><strong>VINHALI</strong></span></h1>\n<h1 style=\"text-align: center;\"><span style=\"color: #ffffff;\"><strong>$host</strong></span></h1>"
  },
  {
   "title": "System uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Informações do sistema" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Tempo que o sistema operacional está ligado"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Zabbix Agent",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Informações de disponibilidade" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Disponibilidade do Agent Zabbix"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "running process",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Informações do sistema" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Número de processos do sistema Operacional"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "number CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Informações do sistema" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Quantidade de CPU" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "latency",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Informações de disponibilidade" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Latência" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "loss pack",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Informações de disponibilidade" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Perda de pacote (Porcentagem)" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Triggers Alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Triggers Alert",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  { "title": "Busy Processes of $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "host" },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Informações de memória" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Memória Disponível" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory in cache",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Informações de memória" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Memória em cache" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": " Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Informações de memória" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Memória em uso" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": " Recognized memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Informações de memória" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Memória Reconhecida" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Informações de memória" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Memória Total" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Trapper Processes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informações de uso do CPU em tempo real"
     },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Tempo de uso do processador CPU [0]"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU/Memory/Disk/Network of $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "host"
  },
  {
   "title": "CPU Time Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": {
      "filter": "Informações de uso do CPU em tempo real"
     },
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Tempo de uso do processador CPU [0]"
     },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "timeField": "@timestamp",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory usage vs Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Informações de memória" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Memória em uso" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Informações de memória" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Memória Disponível" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}